export const REQUEST = 'REQUEST';
export const RECEIVE_SUCCESS = 'RECEIVE_SUCCESS';
export const RECEIVE_FAILURE = 'RECEIVE_FAILURE';

export const UPDATE_VEHICLES = 'UPDATE_VEHICLES';
export const UPDATE_ROUTES = 'UPDATE_ROUTES';
export const SELECT_ROUTE = 'SELECT_ROUTE';
export const UNSELECT_ROUTE = 'UNSELECT_ROUTE';